services:
  base-nix-haskell-builder:
    build:
      context: .
      dockerfile: ./Dockerfile.base-nix-haskell
      args:
        - NIX_CONFIG=$NIX_CONFIG
    image: base-nix-haskell-builder
    container_name: base-nix-haskell-builder
