FROM nixos/nix

RUN mkdir /workspace

WORKDIR /workspace

COPY flake.nix ./flake.nix

ARG NIX_CONFIG

ENV NIX_CONFIG=${NIX_CONFIG}

RUN nix --extra-experimental-features nix-command --extra-experimental-features flakes flake update

RUN nix --extra-experimental-features nix-command --extra-experimental-features flakes build .#test

CMD [ "nix", "--extra-experimental-features", "nix-command", "--extra-experimental-features", "flakes", "build", ".#test.copyToDockerDaemon" ]
